name: rag-Agent
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.12.31=haa95532_0
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cuda-cccl=12.6.77=0
  - cuda-cccl_win-64=12.6.77=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-opencl-dev=12.6.77=0
  - cuda-profiler-api=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - intel-openmp=2023.1.0=h59b6b97_46320
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.7.77=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=3.0.3=h827c3e9_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - openssl=3.4.0=ha4e3fda_1
  - pip=24.2=py310haa95532_0
  - python=3.10.16=h4607a30_1
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - setuptools=75.1.0=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - typing_extensions=4.12.2=py310haa95532_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.40=haa95532_2
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wheel=0.44.0=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.9.5
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.42.0
      - anyio==4.8.0
      - asgiref==3.8.1
      - async-timeout==4.0.3
      - attrs==24.3.0
      - backoff==2.2.1
      - bcrypt==4.2.1
      - beautifulsoup4==4.12.3
      - bs4==0.0.2
      - build==1.2.2.post1
      - cachetools==5.5.0
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.23
      - click==8.1.8
      - cohere==5.13.5
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - cryptography==44.0.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - deprecated==1.2.15
      - distro==1.9.0
      - dnspython==2.7.0
      - durationpy==0.9
      - elastic-transport==8.15.1
      - elasticsearch==8.17.0
      - emoji==2.14.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - fastapi==0.115.6
      - fastavro==1.10.0
      - filelock==3.16.1
      - filetype==1.2.0
      - fireworks-ai==0.15.11
      - flatbuffers==24.12.23
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - google-auth==2.37.0
      - googleapis-common-protos==1.66.0
      - greenlet==3.1.1
      - grpcio==1.68.1
      - h11==0.14.0
      - html5lib==1.1
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.27.0
      - httpx-sse==0.4.0
      - httpx-ws==0.7.1
      - huggingface-hub==0.27.1
      - humanfriendly==10.0
      - idna==3.7
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - jinja2==3.1.5
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpointer==3.0.0
      - kiwisolver==1.4.8
      - kubernetes==31.0.0
      - langchain==0.3.14
      - langchain-anthropic==0.3.1
      - langchain-chroma==0.1.4
      - langchain-cohere==0.3.4
      - langchain-community==0.3.14
      - langchain-core==0.3.29
      - langchain-elasticsearch==0.3.0
      - langchain-experimental==0.3.4
      - langchain-fireworks==0.2.6
      - langchain-huggingface==0.1.2
      - langchain-mongodb==0.3.0
      - langchain-ollama==0.2.2
      - langchain-openai==0.2.14
      - langchain-pinecone==0.2.0
      - langchain-text-splitters==0.3.4
      - langdetect==1.0.9
      - langgraph==0.2.60
      - langgraph-checkpoint==2.0.9
      - langgraph-sdk==0.1.48
      - langsmith==0.1.147
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.24.0
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mmh3==5.0.1
      - monotonic==1.6
      - motor==3.6.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - ndjson==0.3.1
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==1.26.4
      - oauthlib==3.2.2
      - olefile==0.47
      - ollama==0.4.4
      - onnxruntime==1.20.1
      - openai==1.59.3
      - opentelemetry-api==1.29.0
      - opentelemetry-exporter-otlp-proto-common==1.29.0
      - opentelemetry-exporter-otlp-proto-grpc==1.29.0
      - opentelemetry-instrumentation==0.50b0
      - opentelemetry-instrumentation-asgi==0.50b0
      - opentelemetry-instrumentation-fastapi==0.50b0
      - opentelemetry-proto==1.29.0
      - opentelemetry-sdk==1.29.0
      - opentelemetry-semantic-conventions==0.50b0
      - opentelemetry-util-http==0.50b0
      - orjson==3.10.13
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - parameterized==0.9.0
      - pillow==11.1.0
      - pinecone-client==5.0.1
      - pinecone-plugin-inference==1.1.0
      - pinecone-plugin-interface==0.0.7
      - pluggy==1.5.0
      - posthog==3.7.4
      - propcache==0.2.1
      - protobuf==5.29.2
      - psutil==6.1.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydantic-settings==2.7.1
      - pygments==2.18.0
      - pymongo==4.9.2
      - pyparsing==3.2.0
      - pypdf==5.1.0
      - pypdf2==3.0.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - pytest==8.3.4
      - pytest-asyncio==0.25.1
      - python-dateutil==2.9.0.post0
      - python-docx==1.1.2
      - python-dotenv==1.0.1
      - python-iso639==2024.10.22
      - python-magic-bin==0.4.14
      - python-oxmsg==0.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - rapidfuzz==3.11.0
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rsa==4.9
      - safetensors==0.5.1
      - scikit-learn==1.6.0
      - scipy==1.15.0
      - sentence-transformers==3.3.1
      - shellingham==1.5.4
      - simsimd==6.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.36
      - starlette==0.41.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==8.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - typer==0.15.1
      - types-requests==2.32.0.20241016
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - unstructured==0.16.13
      - unstructured-client==0.29.0
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - watchfiles==1.0.3
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==14.1
      - wrapt==1.17.0
      - wsproto==1.2.0
      - yarl==1.18.3
      - zipp==3.21.0
prefix: C:\Users\cerva\miniconda3\envs\rag-Agent
